"""initial schema

Revision ID: 9858a37f948c
Revises: 
Create Date: 2026-07-28 20:43:43.408814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9858a37f948c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('base_response_speed', sa.Float(), nullable=False),
    sa.Column('profile_text', sa.String(length=500), nullable=False),
    sa.Column('reliability_alpha', sa.Float(), nullable=False),
    sa.Column('reliability_beta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_region'), 'providers', ['region'], unique=False)
    op.create_index(op.f('ix_providers_service_type'), 'providers', ['service_type'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=1000), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_state_history_provider_id'), 'provider_state_history', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_state_history_provider_id'), table_name='provider_state_history')
    op.drop_table('provider_state_history')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_providers_service_type'), table_name='providers')
    op.drop_index(op.f('ix_providers_region'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
